/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
import 'vue'
declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: import("vue").DefineComponent<{
        name: {
            type: import("vue").PropType<"accounts" | "advance-expense" | "backup-restore-2" | "cash" | "chart-line" | "chart" | "clearing" | "company" | "dashboard" | "dict" | "fixed-deposit" | "fullscreen-exit" | "fullscreen" | "import" | "interest-rate" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "permission" | "profit-payment" | "save" | "search-detail" | "search" | "summary" | "transfer">;
            default: string;
            required: true;
        };
    }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
        name: {
            type: import("vue").PropType<"accounts" | "advance-expense" | "backup-restore-2" | "cash" | "chart-line" | "chart" | "clearing" | "company" | "dashboard" | "dict" | "fixed-deposit" | "fullscreen-exit" | "fullscreen" | "import" | "interest-rate" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "permission" | "profit-payment" | "save" | "search-detail" | "search" | "summary" | "transfer">;
            default: string;
            required: true;
        };
    }>>, {
        name: "accounts" | "advance-expense" | "backup-restore-2" | "cash" | "chart-line" | "chart" | "clearing" | "company" | "dashboard" | "dict" | "fixed-deposit" | "fullscreen-exit" | "fullscreen" | "import" | "interest-rate" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "permission" | "profit-payment" | "save" | "search-detail" | "search" | "summary" | "transfer";
    }>;
  }
}
