/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"courseware" | "dashboard" | "exam" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "knowledge" | "permission" | "radar" | "safety" | "search" | "skill" | "teacher" | "preserve-color/complete" | "preserve-color/incomplete">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"courseware" | "dashboard" | "exam" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "knowledge" | "permission" | "radar" | "safety" | "search" | "skill" | "teacher" | "preserve-color/complete" | "preserve-color/incomplete">;
          default: string;
          required: true;
      };
  }>>, {
      name: "courseware" | "dashboard" | "exam" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "knowledge" | "permission" | "radar" | "safety" | "search" | "skill" | "teacher" | "preserve-color/complete" | "preserve-color/incomplete";
  }>;
  export const svgNames: ["courseware", "dashboard", "exam", "fullscreen-exit", "fullscreen", "keyboard-down", "keyboard-enter", "keyboard-esc", "keyboard-up", "knowledge", "permission", "radar", "safety", "search", "skill", "teacher", "preserve-color/complete", "preserve-color/incomplete"];
  export type SvgName = "courseware" | "dashboard" | "exam" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "knowledge" | "permission" | "radar" | "safety" | "search" | "skill" | "teacher" | "preserve-color/complete" | "preserve-color/incomplete";
  export default SvgIcon;
}
